### PR TITLE
Overhauled and improved README.md

### PR DESCRIPTION
**Pull request by DsYkX**
To review this PR and all future PRs:
1. Click "Files changed" on the Pull Request in question.
2. Click "Review".
3. Write out the review, which can be a general comment, an approval, or a change request.
4. Select an option. If you approve of the edits, please select "Approve" and submit the review. Without sufficient approvals, changes will not be merged.

### CODE REVIEW

**Review by BakedSausages — DISMISSED** [review]

**Comment by DsYkX** [comment]
Hey, @TeamDsYkX/everything-tycoon please re-approve this PR as I've had to make some minor edits to the text.
When you review commits, please remember to **read through the text** and try to catch any errors that the original contributor has not noticed, or a phrasing change to allow easier reading.
If you find anything that requires changing, please request a change instead of approving or commenting.

**Review by mysterieballing — APPROVED** [review]
It was an informative text explaining all I needed to know so far. Hopefully the contribution.md file will be completed soon, and thank you for inviting me in this project.

**Comment by DsYkX** [comment]
readme.md will likely require the adding of other documentation files momentarily. thus, we are not merging this yet. another approval will be needed when the current ones become stale due to new commits from the changes

**Review by mysterieballing — APPROVED** [review]
(Re-Review)
Understood all the things I needed to know.

**Review by mysterieballing — APPROVED** [review]
no spelling mistakes found

**Pull request merged**
